[client]
showErrorDetails = false

[browser]
serverAddress = "localhost"

[theme]
primaryColor = "#059ff2"
backgroundColor = "#0c417a"
secondaryBackgroundColor = "#06213d"
textColor = "#cfcbc6"
font = "serif"
